### ISSUE TITLE
CRAWDAD Dowload Page Not Found

### ISSUE THREAD

**Issue by qcts33** [caesar0301/city-cellular-traffic-map#1]
The URL listed in the README is unavailable now. Only the 404 page is returned. Also I couldn't find from the search.
So, does the data set still open to download?

**Comment by caesar0301** [comment]
Yes, the data still open! I contacted CRAWDAD admin and got a response of server problem. Thus I publish the data in this repo. "traceset.zip", this is right what u want, the same one on CRAWDAD.

**Comment by qcts33** [comment]
Oh, my bad, I didn't notice that.
Thanks

**Comment by caesar0301** [comment]
: )
